version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
